var expenseTypes=[
    "Vegetables",
    "Fruits",
    "Milk",
    "Curd",
    "Stationary",
    "Mobile Phone",
    "Mobile Recharge",
    "Gas Cylinder",
    "Rice Bag",
    "Kid",
    "Amazon",
"Insurance",
"Chit Fund",
"Education",
"House Rent",
"Grocery",
"Income",
"Department Store",
"Postpaid Bill",
"Gift",
"Car Rent",
"Medical",
"Sweets",
"Driver Fee",
"Honda Activa 125",
"Snacks",
"Petrol",
"Cash Given",
"Festival Dress",
"Dress Purchase",
"Restaurant Bill",
"Parenting"
];
